version: "3"

tasks:
  start:
    desc: Start the mediaserver service
    cmds:
      - sudo systemctl start mediaserver

  stop:
    desc: Stop the mediaserver service
    cmds:
      - sudo systemctl stop mediaserver

  kill:
    desc: Kill stale mediaserver processes (python + mpv)
    cmds:
      - pkill -9 -f "python.*pi_mediaserver" 2>/dev/null || true
      - pkill -9 -f "poetry run mediaserver" 2>/dev/null || true
      - pkill -9 -f mpv 2>/dev/null || true
      - pkill -9 mediaserver 2>/dev/null || true
      - sudo fuser -k /dev/dri/card1 2>/dev/null || true
      - sleep 0.5
      - echo "Killed stale processes"

  restart:
    desc: Restart the mediaserver service
    cmds:
      - sudo systemctl restart mediaserver

  status:
    desc: Show mediaserver service status
    cmds:
      - systemctl status mediaserver --no-pager

  logs:
    desc: Show recent mediaserver logs
    cmds:
      - journalctl -u mediaserver -n 50 --no-pager

  logs:follow:
    desc: Follow mediaserver logs in real-time
    cmds:
      - journalctl -u mediaserver -f

  test:
    desc: Run all tests
    cmds:
      - poetry run pytest

  lint:
    desc: Run linter
    cmds:
      - poetry run ruff check src tests

  dev:
    desc: Run mediaserver directly (not as service)
    cmds:
      - poetry run mediaserver
